### ISSUE TITLE
Emudore64 on a 2.88 MB floppy - is it possible?

### ISSUE THREAD

**Issue by informer2016** [xlar54/emudore64#2]
Hi friend, nice OS you got there! I've noticed that its' ISO size is about 5 MB ...
Please tell, is it possible to somehow compress it to 2.88 MB "fat floppy format"
without losing any functionality? The floppies are still being used even today :
there is open source BIOS _(coreboot+SeaBIOS)_ which supports these
motherboards - https://www.coreboot.org/Supported_Motherboards
With 1 simple command it is possible to add any floppy to existing
open source BIOS build, then you see your wonderful OS as a boot entry ;)
If a "floppy format" is possible, Emudore64 could be launched from a BIOS chip

**Comment by xlar54** [comment]
Im sure it is possible, but I dont think it's going to be a high priority for a long time.  2.88 MB floppies are obviously rarities these days.  Even 1.44MB are getting difficult to source.  And almost no laptops that can run this software would even have a 3 1/2" drive.
